In [1]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data = [[-1, 2], [-.5, 6], [0, 10], [1, 18]]

In [5]:
scaler = MinMaxScaler(feature_range=[5, 10])

In [6]:
result = scaler.fit_transform(data)

In [7]:
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [8]:
scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [9]:
scaler.inverse_transform(data)

array([[-3.4, -7.6],
       [-3.2,  5.2],
       [-3. , 18. ],
       [-2.6, 43.6]])

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [12]:
scaler.mean_

array([-0.125,  9.   ])

In [13]:
scaler.transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [14]:
#将字符型转换成数值标签
from sklearn.preprocessing import LabelEncoder

In [16]:
#特征专用编码
from sklearn.preprocessing import OrdinalEncoder

In [17]:
#独热变量转换成哑变量
from sklearn.preprocessing import OneHotEncoder

## 根据阈值二值化

In [1]:
from sklearn.preprocessing import Binarizer

C:\Users\Administrator\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


## 根据阈值分多份

In [2]:
from sklearn.preprocessing import KBinsDiscretizer

# 特征选择

In [3]:
import pandas as pd
data = pd.read_csv(r"E:\Download\2019机器学习sklearn课堂\3-Digit Recognizer\train.csv")

C:\Users\Administrator\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Administrator\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB


In [5]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [7]:
x = data.iloc[:, 1:]
y = data.iloc[:, 1]

In [8]:
#方差过滤，方差太小表明没有太大影响
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold()

In [9]:
X_var0 = selector.fit_transform(x)

In [13]:
X_var0.shape

(42000, 708)

In [15]:
#找到特征方差中位数后再设为阈值可以过滤一半特征
import numpy as np
selectorm = VarianceThreshold(threshold=np.median(x.var().values))

In [19]:
np.median(x.var())

1352.286703180131

In [16]:
X_varm = selectorm.fit_transform(x)
X_varm.shape

(42000, 392)

In [20]:
#如果是二分类，伯努利随机变量，若p=0.8
X_bar = VarianceThreshold(.8 *(1 - .8)).fit_transform(x)
X_bar.shape

(42000, 685)

In [23]:
#看相关性（标签-特征），卡方， F检验，互信息
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

In [25]:
#卡方不可计算负数，挑选最大K 卡方 的特征
X_chi = SelectKBest(chi2, k=300).fit_transform(X_varm, y)

In [26]:
X_chi.shape

(42000, 300)

In [63]:
chivalue, pvalues_chi = chi2(X=X_varm, y=y)

In [64]:
k = chivalue.shape[0] - (pvalues_chi > .05).sum()

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


In [66]:
#F检验，有分类和回归
from sklearn.feature_selection import f_classif, f_regression

In [68]:
#互信息法，有分类和回归
from sklearn.feature_selection import mutual_info_classif as MIC

In [69]:
MIC(X_varm, y)

array([1.44328993e-15, 1.44328993e-15, 1.44328993e-15, 2.38095238e-05,
       1.19047619e-05, 1.44328993e-15, 2.38095238e-05, 1.19047619e-05,
       1.44328993e-15, 4.76190476e-05, 1.19047619e-05, 5.95238095e-05,
       1.19047619e-04, 2.38095238e-05, 4.76190476e-05, 5.95238095e-05,
       3.57142857e-05, 9.52380952e-05, 1.19047619e-05, 3.57142857e-05,
       1.19047619e-05, 9.52380952e-05, 9.52380952e-05, 4.76190476e-05,
       1.66666667e-04, 1.30952381e-04, 1.78571429e-04, 2.50000000e-04,
       2.85714286e-04, 2.02380952e-04, 3.57142857e-05, 4.76190476e-05,
       3.57142857e-05, 1.19047619e-05, 1.19047619e-05, 1.19047619e-05,
       3.57142857e-05, 4.76190476e-05, 4.76190476e-05, 5.95238095e-05,
       1.54761905e-04, 1.54761905e-04, 3.45238095e-04, 4.40476190e-04,
       3.09523810e-04, 3.69047619e-04, 2.97619048e-04, 2.26190476e-04,
       1.42857143e-04, 1.07142857e-04, 4.76190476e-05, 3.57142857e-05,
       1.19047619e-05, 1.19047619e-05, 1.19047619e-05, 8.33333333e-05,
      

# 使用嵌入法
挑选特征 -> 生成模型评估，循环。
带有特征重要性和惩罚项模型可以使用

In [70]:
from sklearn.feature_selection import SelectFromModel

In [71]:
from sklearn.ensemble import RandomForestClassifier as RFC

In [106]:
rfc = RFC(n_estimators=100, random_state=0)

In [108]:
xembed = SelectFromModel(rfc, threshold=0.001).fit_transform(x, y)

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\feature_selection\_base.py:81: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  UserWarning)


In [109]:
xembed.shape

(42000, 0)

In [88]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# 包装法
特征选择和算法训练同时进行，使用一个目标函数来选择

In [110]:
from sklearn.feature_selection import RFE

In [114]:
#step表示每一步移除的特征数目
selector1 = RFE(rfc, n_features_to_select=340, step=10)

In [115]:
selector1.fit_transform(x, y)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [117]:
 selector1.support_

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [118]:
selector1.ranking_

array([46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30,
       29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1